SINGLE_COURT_WIDTH = 8.23
DOUBLE_COURT_WIDTH = 10.97
HALF_COURT_LENGTH = 11.88
SERVICE_BOX_LENGTH = 6.4
TRAM_LINE_WIDTH = 1.37
SERVICE_BOX_TO_BASELINE_LENGTH = 5.48

NET_POST_HEIGHT = 1.065 # LOOK AT USING NET POST HEIGHT INSTEAD OF PLAYER HEIGHTS FOR TRANSLATING INTO X, Y COORDINATES

PLAYER_1_HEIGHT = 1.88
PLAYER_2_HEIGHT = 1.91